name: Scheduled Notifications

on:
  schedule:
    - cron: "0 9 */14 * *"
  workflow_dispatch:

jobs:
  send_notifications:
    runs-on: ubuntu-latest

    steps:
      - name: Call backend cron endpoint
        run: |
          curl -X POST ${{ vars.CRON_ENDPOINT_URL }} \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
